forum_user_homepage:
    path:     /hello/{name}
    defaults: { _controller: ForumUserBundle:Default:index }
ForumUserBundle_admin:
    resource: "@ForumUserBundle/Resources/config/routing/user.yml"
    prefix:   /admin
