parameters:
#    dawpal_test.example.class: Dawpal\TestBundle\Example

services:
#    dawpal_test.example:
#        class: %dawpal_test.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
