parameters:
#    forum_category.example.class: Forum\CategoryBundle\Example

services:
#    forum_category.example:
#        class: %forum_category.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
