forum_user:
    resource: "@ForumUserBundle/Resources/config/routing.yml"
    prefix:   /

dawpal_test:
    resource: "@DawpalTestBundle/Resources/config/routing.yml"
    prefix:   /

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
