parameters:
#    forum_topic.example.class: Forum\TopicBundle\Example

services:
#    forum_topic.example:
#        class: %forum_topic.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
